### ISSUE TITLE
Encoding issues when installing from Github

### ISSUE THREAD

**Issue by tchakravarty** [yutannihilation/dcR#1]
_[X-posted from here: http://stackoverflow.com/questions/38139808/r-encoding-issues-when-installing-package-from-github]_

I am trying to install the [`dcStockR`](https://github.com/yutannihilation/dcStockR) package from Github, which is an [`htmlwidgets`](http://www.htmlwidgets.org/) wrapper around the [`dc.js`](https://dc-js.github.io/dc.js/) dimensional visualization library: `devtools::install_github("yutannihilation/dcStockR")`. 

I get the following encoding error: 

```
* installing *source* package 'dcStockR' ...
** R
Error in parse(outFile) : 
  C:/Users/tirthankarc/AppData/Local/Temp/Rtmpcz8pHX/devtools153839438c/yutannihilation-dcStockR-c6091c8/R/dc.R:11:59: unexpected input
10: #' @export
11: dc <- function(data, chartRecipe = c("yearlyBubbleChart",ã€
                                                              ^
ERROR: unable to collate and parse R files for package 'dcStockR'
* removing 'C:/Users/tirthankarc/Documents/R/R-3.2.5/library/dcStockR'
Error: Command failed (1)
```

The offending lines of the file in question can be viewed here: https://github.com/yutannihilation/dcStockR/blob/master/R/dc.R#L11.

Two questions: 
- Is this error reproducible for others?
- If so, is there a way to fix this by passing an explicit encoding option to `install.packages`? If not, what other options are available to fix this issue?

**Comment by yutannihilation** [comment]
@tchakravarty 
Thanks for your report and sorry for this error... I've merged #2, so this issue should be fixed now.
Could you confirm?

@dimitris1ps 
Thanks so much for your PR!

**Comment by tchakravarty** [comment]
@yutannihilation Can confirm that the issue is resolved, and I can install the package cleanly.

**Comment by yutannihilation** [comment]
Thanks!
